### ISSUE TITLE
A confusion about html parsing in chrome devtools timeline

### ISSUE THREAD

**Issue by zhangmeng712** [ChromeDevTools/awesome-chrome-devtools#68] opened 2017-12-04 09:18 UTC
Hi Paul
  Thanks for the tips for using chrome devtools, it offers a great help. 
  Recently I‘v using the timeline to check my page, I found something confused, I use `<script type="text/template"> </script>` to hold my underscore template, I found in timeline that it would stop the process of parse Html and trigger  recalculate style and layout , in the real browser working process does it really working in that way and too many  `<script type="text/template">` tags in html affect the performance?

my page is: https://ai.m.taobao.com/
and things happened in line 250 or so

**Comment by Garbee** [comment] 2017-12-06 11:49
All scripts stop the parser. Since the scripts could be doing anything to the document. You should find an alternative way to handle templating.

**Comment by shaggy86** [comment] 2017-12-26 08:11
Duplicate of #

**Closed** 2018-01-02 20:37 UTC
